/**
 * @generated by scripts/architecture-sync.mjs — do not edit.
 *
 * Measured from the tree, so the map's numbers cannot drift from the code.
 * `UNCLAIMED` is what no module on the map covers: run the sync script, then
 * either give an existing module a wider pattern in coverage.json or add the
 * node the repo has been missing.
 */

export const MEASURED: Record<string, { count: number; loc: number }> = {
  'api-foundation': { count: 3, loc: 214 },
  'database-contract': { count: 27, loc: 42089 },
  'document-workspace': { count: 37, loc: 10683 },
  'engineering-map': { count: 41, loc: 7011 },
  'export-toolkit': { count: 15, loc: 882 },
  'extraction-operations': { count: 11, loc: 5307 },
  'ingestion-api': { count: 9, loc: 2081 },
  'model-operations': { count: 23, loc: 5064 },
  'model-settings': { count: 13, loc: 1725 },
  'parsing-http': { count: 12, loc: 1167 },
  'parsing-intake': { count: 7, loc: 908 },
  'parsing-pipeline': { count: 16, loc: 6481 },
  'parsing-storage': { count: 8, loc: 1362 },
  'parsing-verification': { count: 18, loc: 3927 },
  'parsing-workers': { count: 5, loc: 663 },
  'project-api': { count: 7, loc: 1169 },
  'project-store': { count: 12, loc: 5306 },
  'project-workspace': { count: 18, loc: 7608 },
  'shared-contracts': { count: 26, loc: 3836 },
  'simple-parser': { count: 12, loc: 3267 },
  'studio-shell': { count: 2, loc: 101 },
  'ui-kit': { count: 13, loc: 1059 },
}

export const UNCLAIMED: string[] = []
